"""Tests for the 2026-06-08 HubSpot governance helpers in hubspot_client.

Coverage:
  - fix_deal_name(): mojibake repair (em-dash et al.), idempotency, edge cases
  - _build_mojibake_map(): keys are the genuine cp1252 mis-decode sequences
  - _paged_deal_search(): pagination + error handling
  - get_deals_by_filter(): filter construction, closed-stage drop, include_closed
  - get_untagged_deals(): OR filter groups across the 3 governance props

Mojibake strings are GENERATED by replaying the UTF-8->cp1252 corruption
(``ch.encode("utf-8").decode("cp1252")``) rather than hand-typed, because
transport layers silently normalize raw mojibake back to clean characters.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "src"))

from cora.tools import hubspot_client as h  # noqa: E402


def _corrupt(s: str) -> str:
    """Replay the migration corruption on a clean string (UTF-8 bytes read as cp1252)."""
    return s.encode("utf-8").decode("cp1252")


# ---------------------------------------------------------------------------
# Class 1: _build_mojibake_map — keys are genuine corruption sequences
# ---------------------------------------------------------------------------

class TestMojibakeMap:
    def test_em_dash_key_is_real_corruption(self):
        # Em-dash U+2014 -> bytes E2 80 94 -> cp1252 "â€”"
        em_corrupt = _corrupt("—")
        assert em_corrupt in h._MOJIBAKE_FIXES
        assert h._MOJIBAKE_FIXES[em_corrupt] == "—"

    def test_no_key_maps_to_itself(self):
        for bad, good in h._MOJIBAKE_FIXES.items():
            assert bad != good

    def test_no_bare_two_char_prefix_key(self):
        # A 2-char "â€" key would corrupt the longer 3-char keys on replace.
        assert _corrupt("—")[:2] not in h._MOJIBAKE_FIXES

    def test_all_keys_distinct(self):
        keys = list(h._MOJIBAKE_FIXES)
        assert len(keys) == len(set(keys))

    def test_keys_share_prefix_but_differ_in_third_char(self):
        # All keys start with the same 2 chars (â€) but the 3rd char disambiguates.
        thirds = {k[2] for k in h._MOJIBAKE_FIXES if len(k) >= 3}
        assert len(thirds) == len(h._MOJIBAKE_FIXES)


# ---------------------------------------------------------------------------
# Class 2: fix_deal_name behaviour
# ---------------------------------------------------------------------------

class TestFixDealName:
    def test_repairs_em_dash(self):
        corrupt = "American Discount Foods " + _corrupt("—") + " Initial Order"
        assert h.fix_deal_name(corrupt) == "American Discount Foods — Initial Order"

    def test_repairs_en_dash(self):
        corrupt = "A " + _corrupt("–") + " B"
        assert h.fix_deal_name(corrupt) == "A – B"

    def test_repairs_apostrophe(self):
        corrupt = "Jesse" + _corrupt("’") + "s Mart"
        assert h.fix_deal_name(corrupt) == "Jesse’s Mart"

    def test_idempotent_on_clean_em_dash(self):
        clean = "Sprouts — F3E Retail Chain"
        assert h.fix_deal_name(clean) == clean

    def test_idempotent_double_apply(self):
        corrupt = "X " + _corrupt("—") + " Y"
        once = h.fix_deal_name(corrupt)
        assert h.fix_deal_name(once) == once

    def test_plain_ascii_unchanged(self):
        assert h.fix_deal_name("Whole Foods - Retail") == "Whole Foods - Retail"

    def test_empty_string(self):
        assert h.fix_deal_name("") == ""

    def test_none(self):
        assert h.fix_deal_name(None) is None

    def test_multiple_corruptions_in_one_name(self):
        corrupt = _corrupt("’") + "Test" + _corrupt("—") + "End"
        assert h.fix_deal_name(corrupt) == "’Test—End"


# ---------------------------------------------------------------------------
# Class 3: _paged_deal_search — pagination + errors
# ---------------------------------------------------------------------------

def _mock_client(responses: list[dict[str, Any]] | None = None, status: int = 200, text: str = "err"):
    """Build a context-manager httpx.Client mock whose .post returns the given pages."""
    mc = MagicMock()
    mc.__enter__ = lambda s: mc
    mc.__exit__ = MagicMock(return_value=False)
    if responses is not None:
        idx = {"i": 0}

        def _post(*a, **k):
            r = MagicMock()
            r.status_code = 200
            r.json.return_value = responses[idx["i"]]
            idx["i"] += 1
            return r

        mc.post.side_effect = _post
    else:
        r = MagicMock()
        r.status_code = status
        r.text = text
        r.json.return_value = {"results": []}
        mc.post.return_value = r
    return mc


class TestPagedDealSearch:
    def test_single_page(self):
        page = {"results": [{"id": "1", "properties": {}}]}
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=_mock_client([page])):
                out = h._paged_deal_search([{"filters": []}], ["dealname"])
        assert len(out) == 1

    def test_follows_pagination(self):
        page1 = {"results": [{"id": "1", "properties": {}}], "paging": {"next": {"after": "c2"}}}
        page2 = {"results": [{"id": "2", "properties": {}}]}
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=_mock_client([page1, page2])):
                out = h._paged_deal_search([{"filters": []}], ["dealname"])
        assert {d["id"] for d in out} == {"1", "2"}

    def test_respects_max_deals(self):
        page1 = {"results": [{"id": "1", "properties": {}}, {"id": "2", "properties": {}}],
                 "paging": {"next": {"after": "c2"}}}
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=_mock_client([page1])):
                out = h._paged_deal_search([{"filters": []}], ["dealname"], max_deals=1)
        assert len(out) == 1

    def test_401_raises(self):
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=_mock_client(status=401)):
                with pytest.raises(h.HubSpotClientError, match="401"):
                    h._paged_deal_search([{"filters": []}], ["dealname"])

    def test_500_raises(self):
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=_mock_client(status=500)):
                with pytest.raises(h.HubSpotClientError):
                    h._paged_deal_search([{"filters": []}], ["dealname"])

    def test_network_error_raises(self):
        import httpx
        mc = MagicMock()
        mc.__enter__ = lambda s: mc
        mc.__exit__ = MagicMock(return_value=False)
        mc.post.side_effect = httpx.RequestError("boom")
        with patch("cora.tools.hubspot_client._token", return_value="t"):
            with patch("httpx.Client", return_value=mc):
                with pytest.raises(h.HubSpotClientError, match="network error"):
                    h._paged_deal_search([{"filters": []}], ["dealname"])


# ---------------------------------------------------------------------------
# Class 4: get_deals_by_filter
# ---------------------------------------------------------------------------

_STAGE_CACHE = {
    "3760235201": "Identify",
    "3760235204": "Qualified",
    "3760235206": "Closed Won",
    "3760235207": "Closed Lost",
}


class TestGetDealsByFilter:
    def _deal(self, did, stage, **props):
        return {"id": did, "properties": {"dealstage": stage, **props}}

    def test_builds_all_filters(self):
        captured = {}

        def _fake_search(filter_groups, properties, max_deals=200):
            captured["fg"] = filter_groups
            return []

        with patch("cora.tools.hubspot_client._STAGE_NAME_CACHE", _STAGE_CACHE):
            with patch("cora.tools.hubspot_client._paged_deal_search", side_effect=_fake_search):
                h.get_deals_by_filter(entity="F3E", direction="revenue_in",
                                      owner_id="162944825", stage_id="3760235204",
                                      pipeline_id="2313722582")
        filters = captured["fg"][0]["filters"]
        names = {f["propertyName"]: f["value"] for f in filters}
        assert names["f3_entity"] == "F3E"
        assert names["f3_deal_direction"] == "revenue_in"
        assert names["hubspot_owner_id"] == "162944825"
        assert names["dealstage"] == "3760235204"
        assert names["pipeline"] == "2313722582"

    def test_no_filters_sends_empty_group(self):
        captured = {}
        with patch("cora.tools.hubspot_client._STAGE_NAME_CACHE", _STAGE_CACHE):
            with patch("cora.tools.hubspot_client._paged_deal_search",
                       side_effect=lambda fg, p, max_deals=200: captured.setdefault("fg", fg) or []):
                h.get_deals_by_filter()
        assert captured["fg"] == [{"filters": []}]

    def test_drops_closed_by_default(self):
        deals = [self._deal("1", "3760235204"), self._deal("2", "3760235206"),
                 self._deal("3", "3760235207")]
        with patch("cora.tools.hubspot_client._STAGE_NAME_CACHE", _STAGE_CACHE):
            with patch("cora.tools.hubspot_client._paged_deal_search", return_value=deals):
                out = h.get_deals_by_filter(entity="F3E")
        ids = {d["id"] for d in out}
        assert ids == {"1"}

    def test_include_closed_keeps_all(self):
        deals = [self._deal("1", "3760235204"), self._deal("2", "3760235206")]
        with patch("cora.tools.hubspot_client._STAGE_NAME_CACHE", _STAGE_CACHE):
            with patch("cora.tools.hubspot_client._paged_deal_search", return_value=deals):
                out = h.get_deals_by_filter(entity="F3E", include_closed=True)
        assert len(out) == 2

    def test_refreshes_cache_when_empty(self):
        with patch("cora.tools.hubspot_client._STAGE_NAME_CACHE", {}):
            with patch("cora.tools.hubspot_client._refresh_pipeline_cache") as refresh:
                with patch("cora.tools.hubspot_client._paged_deal_search", return_value=[]):
                    h.get_deals_by_filter(entity="F3E")
        refresh.assert_called_once()


# ---------------------------------------------------------------------------
# Class 5: get_untagged_deals
# ---------------------------------------------------------------------------

class TestGetUntaggedDeals:
    def test_or_groups_for_three_props(self):
        captured = {}
        with patch("cora.tools.hubspot_client._paged_deal_search",
                   side_effect=lambda fg, p, max_deals=200: captured.setdefault("fg", fg) or []):
            h.get_untagged_deals()
        fg = captured["fg"]
        # One filter group per governance prop (OR semantics), each NOT_HAS_PROPERTY
        assert len(fg) == 3
        props = {g["filters"][0]["propertyName"] for g in fg}
        assert props == {"f3_entity", "f3_deal_direction", "hjr_deal_type"}
        for g in fg:
            assert g["filters"][0]["operator"] == "NOT_HAS_PROPERTY"

    def test_returns_results(self):
        with patch("cora.tools.hubspot_client._paged_deal_search",
                   return_value=[{"id": "9", "properties": {}}]):
            out = h.get_untagged_deals()
        assert out and out[0]["id"] == "9"


# ---------------------------------------------------------------------------
# Class 6: no duplicate create_note definition remains
# ---------------------------------------------------------------------------

class TestNoDuplicateCreateNote:
    def test_create_note_defined_once(self):
        src = (Path(h.__file__)).read_text(encoding="utf-8")
        assert src.count("def create_note(") == 1
