#!/usr/bin/env python3
"""Monday 7:30am AZ — Finance Weekly recap generator and poster.

Pulls Fireflies transcript chunks for the most recent Finance Weekly meeting
from the KB, synthesizes a structured recap via Claude Haiku, and posts it
to #hjrg-finance (C0B3V5SDNAG) — either immediately or via chat.scheduleMessage
so it lands at 8:00am AZ (15:00 UTC) if fired early.

Channel is HARDCODED to C0B3V5SDNAG. No fallback to any other channel.
If the channel post fails, the script logs an error and exits — it does NOT
attempt to post elsewhere.

Dedup: skips the run if a recap was already sent during the current ISO week.

Usage:
    .venv\\Scripts\\python.exe scripts\\run_finance_weekly_recap.py
    .venv\\Scripts\\python.exe scripts\\run_finance_weekly_recap.py --dry-run
    .venv\\Scripts\\python.exe scripts\\run_finance_weekly_recap.py --force

Registered as Windows Task Scheduler task: cowork-cora-finance-weekly
Schedule: Every Monday 7:30am AZ (14:30 UTC)
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sqlite3
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path

from dotenv import load_dotenv

_REPO_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(_REPO_ROOT / ".env", override=True)
sys.path.insert(0, str(_REPO_ROOT / "src"))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(
            _REPO_ROOT / "logs" / f"finance-weekly-{datetime.now().strftime('%Y-%m-%d')}.log",
            encoding="utf-8",
        ),
    ],
)
log = logging.getLogger("finance-weekly")

# ── Constants ──────────────────────────────────────────────────────────────────

_FINANCE_CHANNEL_ID = "C0B3V5SDNAG"   # #hjrg-finance — hardcoded, no fallback
_KB_DB = _REPO_ROOT / "data" / "cora_kb.db"
_DEDUP_PATH = _REPO_ROOT / "data" / "cache" / "finance-weekly-sent.json"
_LOOKBACK_DAYS = 7
_MAX_CHUNKS = 30
_MAX_CHUNK_CHARS = 400
# Monday 15:00 UTC = 8:00am AZ (MST, UTC-7); post_at must be ≥5 min in future
_TARGET_HOUR_UTC = 15
_TARGET_MINUTE_UTC = 0

_HAIKU_MODEL = "claude-haiku-4-5-20251001"

_RECAP_PROMPT = """\
You are Cora, a financial and operational assistant for HJR Global and its portfolio companies.

Below are excerpts from the Finance Weekly meeting transcripts and financial communications from the past 7 days:

---
{chunks_text}
---

Write a concise Finance Weekly recap for the #hjrg-finance Slack channel.
Structure it exactly as follows (use emoji headers, plain Slack text — no markdown headers):

🏆 *Wins this week*
• [List material positive outcomes, resolved items, confirmed payments, IRS wins, etc.]

🔴 *Open decisions / action items*
• [List items where action is needed or decisions are pending. Include owner if mentioned.]

📅 *Upcoming / watch list*
• [List upcoming deadlines, meetings, filings, or items to monitor.]

⚠️ *Flags*
• [List any risks, overdue items, or items needing Harrison's attention.]

Rules:
- Be specific — reference real numbers, names, and dates from the excerpts above.
- Do NOT include PHI or client-level health information.
- Do NOT mention Visibility CPA team members in a way that identifies their advice.
- Do NOT fabricate facts not present in the excerpts.
- Keep each section to 3-5 bullets maximum. Total length: 300-500 words.
- If a section has nothing material, write "• Nothing new this week."
- End with a single line: _Recap generated by Cora from Finance Weekly transcript._
"""


# ── DB helpers ─────────────────────────────────────────────────────────────────

def _fetch_finance_chunks(lookback_days: int = _LOOKBACK_DAYS) -> list[str]:
    """Query KB for Fireflies chunks related to Finance Weekly from the past N days."""
    if not _KB_DB.exists():
        log.warning("KB not found at %s — no chunks available", _KB_DB)
        return []
    cutoff = int(time.time() - lookback_days * 86400)
    conn = sqlite3.connect(str(_KB_DB))
    try:
        # Primary: chunks explicitly about finance weekly
        rows = conn.execute(
            """
            SELECT content FROM knowledge_chunks
            WHERE source = 'fireflies'
              AND entity IN ('FNDR', 'HJRG')
              AND ingested_at >= ?
              AND (
                LOWER(content) LIKE '%finance weekly%'
                OR LOWER(title)  LIKE '%finance weekly%'
                OR LOWER(content) LIKE '%visibility%'
                OR LOWER(content) LIKE '%cash flow%'
                OR LOWER(content) LIKE '%irs%'
                OR LOWER(content) LIKE '%payroll%'
              )
            ORDER BY ingested_at DESC
            LIMIT ?
            """,
            (cutoff, _MAX_CHUNKS),
        ).fetchall()
        if not rows:
            # Fallback: any recent HJRG/FNDR fireflies chunks
            log.info("No finance-specific chunks found — falling back to all HJRG Fireflies chunks")
            rows = conn.execute(
                """
                SELECT content FROM knowledge_chunks
                WHERE source = 'fireflies'
                  AND entity IN ('FNDR', 'HJRG')
                  AND ingested_at >= ?
                ORDER BY ingested_at DESC
                LIMIT ?
                """,
                (cutoff, _MAX_CHUNKS),
            ).fetchall()
    finally:
        conn.close()

    excerpts = []
    for (content,) in rows:
        if content:
            excerpts.append(content[:_MAX_CHUNK_CHARS].replace("\n", " ").strip())
    log.info("Fetched %d KB chunks for recap synthesis", len(excerpts))
    return excerpts


# ── Dedup ──────────────────────────────────────────────────────────────────────

def _iso_week() -> str:
    """Return ISO year-week string e.g. '2026-W23'."""
    now = datetime.now()
    return f"{now.year}-W{now.isocalendar()[1]:02d}"


def _already_sent_this_week() -> bool:
    _DEDUP_PATH.parent.mkdir(parents=True, exist_ok=True)
    try:
        data = json.loads(_DEDUP_PATH.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        data = {}
    return data.get("last_week") == _iso_week()


def _mark_sent() -> None:
    _DEDUP_PATH.parent.mkdir(parents=True, exist_ok=True)
    _DEDUP_PATH.write_text(
        json.dumps({"last_week": _iso_week(), "sent_at": int(time.time())}),
        encoding="utf-8",
    )


# ── Synthesis ──────────────────────────────────────────────────────────────────

def _synthesize_recap(chunks: list[str], api_key: str) -> str:
    """Call Claude Haiku to generate the Finance Weekly recap."""
    if not chunks:
        return (
            "*Finance Weekly Recap*\n\n"
            "No Finance Weekly transcript found in the knowledge base this week. "
            "Please ensure the Fireflies transcript has been synced.\n\n"
            "_Recap generated by Cora._"
        )
    import anthropic
    chunks_text = "\n\n".join(f"- {c}" for c in chunks)
    prompt = _RECAP_PROMPT.format(chunks_text=chunks_text)
    client = anthropic.Anthropic(api_key=api_key)
    msg = client.messages.create(
        model=_HAIKU_MODEL,
        max_tokens=800,
        messages=[{"role": "user", "content": prompt}],
    )
    return (msg.content[0].text or "").strip()


# ── Slack posting ──────────────────────────────────────────────────────────────

def _next_monday_8am_utc() -> int:
    """Return Unix timestamp for next Monday 15:00 UTC (8am AZ MST)."""
    now = datetime.now(timezone.utc)
    days_until_monday = (7 - now.weekday()) % 7 or 7
    target = now.replace(hour=_TARGET_HOUR_UTC, minute=_TARGET_MINUTE_UTC, second=0, microsecond=0)
    target += timedelta(days=days_until_monday)
    return int(target.timestamp())


def _should_schedule(dry_run: bool) -> tuple[bool, int]:
    """Return (should_schedule, post_at_epoch). Schedule if it's before 15:00 UTC Monday."""
    if dry_run:
        return False, 0
    now = datetime.now(timezone.utc)
    is_monday = now.weekday() == 0
    is_before_target = now.hour < _TARGET_HOUR_UTC or (
        now.hour == _TARGET_HOUR_UTC and now.minute < _TARGET_MINUTE_UTC
    )
    if is_monday and is_before_target:
        # Schedule for 15:00 UTC today
        target = now.replace(hour=_TARGET_HOUR_UTC, minute=_TARGET_MINUTE_UTC, second=0, microsecond=0)
        mins_until = (target - now).total_seconds() / 60
        if mins_until >= 5:
            return True, int(target.timestamp())
    return False, 0


def _post_recap(text: str, dry_run: bool, bot_token: str) -> None:
    """Post the recap to #hjrg-finance. Schedule if conditions are right; else post immediately."""
    from slack_sdk import WebClient
    from slack_sdk.errors import SlackApiError

    if dry_run:
        print("\n" + "=" * 60)
        print(f"[DRY RUN] Would post to #hjrg-finance ({_FINANCE_CHANNEL_ID}):")
        print("=" * 60)
        print(text)
        print("=" * 60)
        return

    # B1: this script uses WebClient but imports no cora.* module, so the
    # class-level egress patch (installed from cora/__init__.py) never runs in this
    # process. Sanitize the body explicitly so it can't egress unsanitized.
    # WS-5: Haiku is prompted for Slack *bold* but can still emit literal ** --
    # normalize alongside the explicit sanitize (idempotent on already-correct text).
    from cora.slack_egress import sanitize_text  # noqa: PLC0415
    from cora.reply_formatter import normalize_slack_bold  # noqa: PLC0415
    client = WebClient(token=bot_token)
    text = normalize_slack_bold(sanitize_text(text))
    should_sched, post_at = _should_schedule(dry_run)

    try:
        if should_sched:
            resp = client.chat_scheduleMessage(
                channel=_FINANCE_CHANNEL_ID,
                text=text,
                post_at=post_at,
                unfurl_links=False,
                unfurl_media=False,
            )
            sched_ts = datetime.fromtimestamp(post_at, tz=timezone.utc).strftime("%H:%M UTC")
            log.info("Finance Weekly recap scheduled for %s (ts=%s)", sched_ts, resp.get("scheduled_message_id"))
        else:
            resp = client.chat_postMessage(
                channel=_FINANCE_CHANNEL_ID,
                text=text,
                unfurl_links=False,
                unfurl_media=False,
            )
            log.info("Finance Weekly recap posted immediately (ts=%s)", resp.get("ts"))
    except SlackApiError as exc:
        log.error("Failed to post Finance Weekly recap to #hjrg-finance: %s", exc)
        sys.exit(1)


# ── Main ───────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Print recap without posting")
    parser.add_argument("--force", action="store_true", help="Skip dedup check and post regardless")
    args = parser.parse_args()

    log.info("=== Finance Weekly Recap starting (dry_run=%s force=%s) ===", args.dry_run, args.force)

    if not args.force and not args.dry_run and _already_sent_this_week():
        log.info("Already sent this week (%s) — skipping. Use --force to override.", _iso_week())
        return 0

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        log.error("ANTHROPIC_API_KEY not set")
        return 1

    bot_token = os.environ.get("SLACK_BOT_TOKEN", "")
    if not bot_token and not args.dry_run:
        log.error("SLACK_BOT_TOKEN not set")
        return 1

    chunks = _fetch_finance_chunks()
    log.info("Synthesizing recap from %d chunks...", len(chunks))
    recap = _synthesize_recap(chunks, api_key)
    log.info("Recap synthesized (%d chars)", len(recap))

    _post_recap(recap, args.dry_run, bot_token)

    if not args.dry_run:
        _mark_sent()
        log.info("Dedup record written for week %s", _iso_week())

    log.info("=== Finance Weekly Recap complete ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
